CREATE TABLE IF NOT EXISTS ar_1999 (
    "CODIGO" INTEGER,
    "DIST_CONC_FREG" TEXT,
    "T_ELEI" TEXT,
    "D_ELEI" TEXT,
    "SIGLA" TEXT,
    "T_DADOS" TEXT,
    "VOTOS" INTEGER,
    "P_VOTOS" NUMERIC,
    "MANDATOS" INTEGER
);